Resolve #8
NASA-PDS/github-actions-base pull request #9
Opened 2021-07-14 16:02 UTC by nutjob4life

##  📜 Summary

Merge this if you dare to resolve #8.

## 🩺 Test Data and/or Report

There's no way to test this without a massive test harness (which would include: GitHub Actions ecosystem, actions runners, virtual machines, image registries, etc.). Yeah, there's [nektos/act GitHub actions runner](https://github.com/nektos/act), but I haven't been able to get it to work yet—meaning I haven't had _time_ to get it to work, and the sprint deadline looms.

## 🧩 Related Issues

- #8

2021-07-14 17:31 UTC, collinss-jpl approved these changes

2021-07-14 18:19 UTC, jordanpadams requested changes
@nutjob4life can we update the README with how to do this?

2021-07-14 18:41 UTC, nutjob4life commented
@jordanpadams see the latest commit de916db54f789ea388e2a89c79074b671c8d9bb7

2021-07-15 20:42 UTC, tloubrieu-jpl approved these changes
Right, we'll test in production, it is only CI/CD stuff anyway ;)

2021-07-15 20:42 UTC, merged